--run_once("xrandr --output VGA-0 --mode 1280x1024 --pos 0x0 --output LVDS --mode 1024x600 --pos 1280x0")
run_once(os.getenv("HOME") .. "/.dropbox-dist/dropboxd")
--run_once("xscreensaver", "-no-splash")
run_once("skype")
--run_once("xautolock -time 10 -locker 'sh " .. bin .. "lock.sh' &")
run_once("wmname LG3D")
run_once("compton -cGb &")
run_once("(sleep 2 && spacefm -d) &")
--run_once("wicd-client --tray")